# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-10-27 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['idreg', 'nombre'],
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='lugarTuristico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('zoom', models.CharField(max_length=100)),
                ('iddep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteTour.departamento')),
            ],
            options={
                'ordering': ['iddep', 'nombre'],
                'verbose_name': 'Lugar Turistico',
                'verbose_name_plural': 'Lugares Turisticos',
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='idreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteTour.region'),
        ),
    ]
