# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-10-27 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteTour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='lugarturistico',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='region',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
